#! /bin/bash

export VERSION="2026-0"
export SYSTEM_DESC="Kazeta"
export SYSTEM_NAME="kazeta"
export USERNAME="gamer"
export SIZE="5000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://kazeta.org"
export DOCUMENTATION_URL="https://kazeta.org"
export BUG_REPORT_URL="https://github.com/kazetaos/kazeta/issues"

export KERNEL_PACKAGE="linux"

export PACKAGES="\
	fuse2 \
	fuse3 \
	gamescope \
	greetd \
	htop \
	inputplumber \
	less \
	lib32-libxfixes \
	lib32-nvidia-utils \
	lib32-pipewire \
	lib32-vulkan-intel \
	lib32-vulkan-radeon \
	linux-firmware \
	nvidia-open \
	nvidia-utils \
	pipewire-jack \
	pipewire-pulse \
	pipewire-alsa \
	rtkit \
	sudo \
	vim \
	vulkan-intel \
	vulkan-radeon \
	which \
	wireplumber \
"

export AUR_PACKAGES="\
	downgrade \
	frzr \
	pikaur \
	udev-media-automount \
"

export SERVICES="\
	fstrim.timer \
	greetd \
	inputplumber \
	systemd-networkd \
	systemd-resolved \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers

	# Disable SPDIF/IEC958 audio output
	sed -e '/\[Mapping iec958/,+5 s/^/#/' -i '/usr/share/alsa-card-profile/mixer/profile-sets/default.conf'

	# Set a default timezone, FNA/XNA (and probably others) need it
	ln -s /usr/share/zoneinfo/UTC /etc/localtime

	# Persist kazeta save data
	mkdir -p /home/${USERNAME}/.local/share
	ln -s /var/kazeta /home/${USERNAME}/.local/share/kazeta

	# Persist wireplumber settings
	mkdir -p /home/${USERNAME}/.local/state
	ln -s /var/kazeta/state/wireplumber /home/${USERNAME}/.local/state/wireplumber

	# Set permissions
	chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}

	# Automount storage to /run/media
	sed -i -e 's,mediadir=/media,mediadir=/run/media,' /usr/bin/media-automount

	# Drop filesystem type from mount directory name
	sed -i -e 's,}.$TYPE",}",' /usr/bin/media-automount

	# Fix failure to mount SD cards flashed with disk images
	sed -i -e 's,mmcblk\[0-9\]p\[0-9\],mmcblk\[0-9\]\*,' /usr/lib/udev/rules.d/99-media-automount.rules

	# Add support for automounting optical media
	echo 'KERNEL=="sr[0-9]*", ACTION=="change",	RUN+="/usr/bin/systemctl --no-block restart media-automount@%k.service"' >> /usr/lib/udev/rules.d/99-media-automount.rules

	# Force Xbox 360 emulation for all controller devices
	sed -i -e 's/- hori-steam/- xbox-series/' /usr/share/inputplumber/devices/*.yaml
	sed -i -e 's/- gamepad/- xbox-series/' /usr/share/inputplumber/devices/*.yaml
	sed -i -e 's/- deck-uhid/- xbox-series/' /usr/share/inputplumber/devices/*.yaml
	sed -i -e 's/- deck/- xbox-series/' /usr/share/inputplumber/devices/*.yaml
	sed -i -e 's/- xbox-elite/- xbox-series/' /usr/share/inputplumber/devices/*.yaml
	sed -i -e 's/- xb360/- xbox-series/' /usr/share/inputplumber/devices/*.yaml
	sed -i -e 's/- ds5-edge/- xbox-series/' /usr/share/inputplumber/devices/*.yaml
	sed -i -e 's/- ds5/- xbox-series/' /usr/share/inputplumber/devices/*.yaml

	# Create system users and avoid failure at runtime due to read-only file system
	systemd-sysusers
	systemctl mask systemd-sysusers.service
}
