wireplumber.settings = {
  device.routes.default-sink-volume = 0.9
}

monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output\\..*\\.hdmi.*" }
    ]
    actions = {
      update-props = {
        priority.session = 1300
      }
    }
  }
  {
    matches = [
      { node.name = "~alsa_output\\.usb-.*" }
    ]
    actions = {
      update-props = {
        priority.session = 1400
      }
    }
  }
]
